server:
  port: 8082

eureka:
  # This forces the service to register with its IP address, not its hostname.
  prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0